import { ACCOUNT_SOURCE, NETWORK_PRESETS, ROUTES } from './constants.js';

export const state = {
  api: null,
  selectedAccount: null,
  accountsLoaded: false,
  lastLoadedAccounts: [],
  accountSource: ACCOUNT_SOURCE.WALLET,
  /** Selected `window.injectedWeb3` key before loading accounts (Wallet mode). */
  walletExtensionKey: null,
  networkPresetValue: NETWORK_PRESETS[0].url,
  palletSelectValue: '',
  methodSelectValue: '',
  qPalletSelectValue: '',
  qStorageSelectValue: '',
  cPalletSelectValue: '',
  cConstantSelectValue: '',
  activeRoute: ROUTES.EXPLORER,
  preflightChecks: [],
  timelineEvents: [],
  drafts: [],
  explorerBlocks: [],
  explorerSelectedHash: null,
  explorerLive: true,
  explorerUnsub: null,
  batchQueue: [],
  watches: [],
  eventStreamUnsub: null,
  eventStreamFilter: '',
  eventStreamEvents: [],
  finalizedHead: null,
  finalizedUnsub: null,
  addressBook: [],
};
